version: "3.2"
services:
  backend:
    # image: ghcr.io/goosebumpsrust/goosebumpsbackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint:
      - SOLANA_KEY=${SOLANA_KEY}
    ports:
     - "8080:8080"
