version: "3.2"
services:
  backend:
    # image: ghcr.io/goosebumpsrust/goosebumpsbackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    env_file:
      - .env
    environment:
      - ETH_NODE=${ETH_NODE}
      - ETH_KEY=${ETH_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
